spring.application.name=api-gateway
eureka.client.service-url.defaultZone=http://admin:admin@discovery-service:8761/eureka

logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE

# user hits: http://localhost:8080/api/product -> http://localhost:{random-port}/api/product
spring.cloud.gateway.server.webflux.routes[0].id=product-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/product/**

spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/order/**

spring.cloud.gateway.server.webflux.routes[2].id=inventory-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://inventory-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/inventory/**



# user hits: http://localhost:8080/eureka/web -> http://localhost:8761

spring.cloud.gateway.server.webflux.routes[3].id=discovery-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://discovery-service:8761
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/eureka/web
spring.cloud.gateway.server.webflux.routes[3].filters[0]=SetPath=/


# I hit this in my browser -> http://localhost:8080/eureka/web
# This will go to Gateway.
# Gateway sees /eureka/web and decides to forward request to: http://localhost:8761 (eureka server)
# When we hit that, we get html file which has css, js and images files included in it.
# Html file will be forwarded to the browser from the server.
# Browser sees the css and js files and asks for them -> http://localhost:8080/eureka/css/wro.css and http://localhost:8080/eureka/js/wro.js
# These will again go to the Gateway.
# Gateway see /eureka/css/wro.css and eureka/js/wro.js in requests.
# But Gateway can't find any mappings to these paths in routing, So these are not hit.
# Remaining html file loads perfectly.

#Browser → Gateway → Eureka (Request)
#Browser ← Gateway ← Eureka (Response)




# browser hits http://localhost:8080/eureka/css/wro.css and http://localhost:8080/eureka/js/wro.js etc...
# Gateway intercepts, sees eureka/css/** and eureka/js/** and finds it in routing with /eureka/**
# Gateway forwards it to http://localhost:8761/eureka/css/**, http://localhost:8761/eureka/js/** and gets the response
# Then gateway sends back those files again to browser and the UI is fully loaded.

spring.cloud.gateway.server.webflux.routes[4].id=discovery-service-fully-loaded
spring.cloud.gateway.server.webflux.routes[4].uri=http://discovery-service:8761
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/eureka/**


# By this link, our resource server(Gateway) know who is my Authorization Server is.
# This endpoint has a JSON, which contains all the details. Ex: token endpoint, introspect endpoint etc.
# So, Resource Server(Gateway) download this full JSON while starting.
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/spring-boot-microservices-realm