version: "3.8"

services:
  product-mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8090:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - product-mongodb
    networks:
      - backend

  product-service:
    build: .
    container_name: product-service
    environment:
      - DT_SERVICE_NAME=product-service
    ports:
      - "8083:8083"
    depends_on:
      - product-mongodb
    networks:
      - backend

volumes:
  mongo_data:
    driver: local

networks:
  backend:
    external: true
    name: microservices-net