spring.application.name=inventory-service

server.port=8081

spring.datasource.url=jdbc:mysql://inventory-mysql:3306/inventory-service
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Auto creates/updates tables using Entities in code
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#By default, spring will take below URL, not required explicitly unless you change the url of eureka.
#Best practice is to mention the url
eureka.client.service-url.defaultZone=http://admin:admin@discovery-service:8761/eureka

#Generates the instance-id as unique if we run multiple instances in local, By this uniqueness it will be easy for eureka to register services
eureka.instance.instance-id=${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}