version: "3.8"

services:
  inventory-mysql:
    image: mysql:8.0
    container_name: inventory-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory-service
    volumes:
      - inventory_mysql_data:/var/lib/mysql
    networks:
      - backend

  adminer:
    image: adminer
    container_name: mysql-adminer-inventory
    restart: always
    ports:
      - "8092:8080"
    depends_on:
      - inventory-mysql
    networks:
      - backend

  inventory-service:
    build: .
    container_name: inventory-service
    environment:
      - DT_SERVICE_NAME=inventory-service
    ports:
      - "8081:8081"
    depends_on:
      - inventory-mysql
    networks:
      - backend

volumes:
  inventory_mysql_data:
    driver: local

networks:
  backend:
    external: true
    name: microservices-net